// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ystqoqxhgcvaukavsyqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdHFvcXhoZ2N2YXVrYXZzeXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDU0MDksImV4cCI6MjA2MzY4MTQwOX0.Q1pg91NSVT9l7FjRPp64AVwuk-CZz5ql7zUMAP-DxOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);